### ISSUE TITLE
OU handeling + Error "Insufficient Access Rights"

### ISSUE THREAD

**Issue by jdor300** [GSLabDev/terraform-provider-ad#1]
Hey,

I saw at the ReadMe file that you will work on other features than adding a computer account to the AD.
the most importent thing is not just to add a computer account to the AD, it's to add it to a certain OU under the domain. ths feature will be effective in so many ways, and will make this provider usefull.

Other than that,
i ran into an error :

> ad_computer.myserver: Error while adding a computer to the AD LDAP Result Code 50 'Insufficient Access Rights'

```
my CODE :
provider "ad" {
 domain="my.domain"
 user="myuser"
 password="mypassword"
 ip="192.168.3.3"
}
resource "ad_computer" "myserver" {
 domain="mydomain"
 computer_name="myserver"
}
```

Important to say that i have full permissions on my Active Directory interface, also Domain Admin.

**Comment by Outek** [comment]
Create a computer account in a specific OU and remove it from there would be very helpful.

**Comment by bhushan-rane** [comment]
> 
> 
> Create a computer account in a specific OU and remove it from there would be very helpful.

@Outek added new resource to create computer account in specific OU and remove it.
