### ISSUE TITLE
make build problems

### ISSUE THREAD

**Issue by marrik96** [GSLabDev/terraform-provider-ad#11]
Hello,  having trouble building the binary.  System is Ubuntu 18.04 and followed instructions to install go, clone repo, make build.  Make build does not produce any errors but I'm not seeing an ".exe" to copy to terraform providers folder.  I'm not faimilar with Go language, just have need to use AD provider to pre-stage computer objects during terraform builds.

Thank you for any assists.

**Comment by samtholiya** [comment]
@marrik96 you should check for a linux binary in ubuntu instead of a .exe binary which is in windows case

**Comment by marrik96** [comment]
Got it.  Do you know if there is a way to get a pre-built windows binary of this provider?  I run terraform from windows 64bit.  Thanks.

**Comment by samtholiya** [comment]
One way is you can build on windows other is follow the steps here https://github.com/golang/go/wiki/WindowsCrossCompiling although I have not tried this but looks promising

**Comment by marrik96** [comment]
Thanks for info!
