### ISSUE TITLE
Add LDAPS support ?

### ISSUE THREAD

**Issue by jpatigny** [GSLabDev/terraform-provider-ad#18]
Hello,

Is there any plan to support LDAP over SSL (port 686) in addition to LDAP ?
It is unfortunately required for me.

Thanks in advance for your feedback.

**Comment by samtholiya** [comment]
@jpatigny that is not what we are developing but we are open to contributions. 😊

**Comment by dembaca** [comment]
@samtholiya I added a PR that would allow LDAPS https://github.com/GSLabDev/terraform-provider-ad/pull/23
