### ISSUE TITLE
ceating Domain Local group ad_group_to_ou against and existing Group

### ISSUE THREAD

**Issue by raggarichie** [GSLabDev/terraform-provider-ad#33]
Is there a way to create a Domain Local security Group instead of the default Global Security group? I'm able to create groups in under the groups OU using this code, but i've been pulling out my hair trying to figure out which file or if its possible to change this from Global Security  group to domainlocal. The AD team prefers domain local because we have multiple domains and the groups that we are creating should be domain local following their strict AD polices.

**Comment by bhushan-rane** [comment]
@raggarichie this is not possible as of now.
